language: node_js
node_js:
  - '0.10'
env:
  global:
    - NODE_ENV=test
before_install:
  - npm install -g karma-cli
  - npm install -g mocha
  - npm install -g gulp
  - npm install -g bower
before_script:
  - bower install
